// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/think-inn-variants/InovasyonFeed.tsx": () => import("../components/mockups/think-inn-variants/InovasyonFeed.tsx"),
  "./components/mockups/think-inn-variants/KanbanTahtasi.tsx": () => import("../components/mockups/think-inn-variants/KanbanTahtasi.tsx"),
  "./components/mockups/think-inn-variants/KaranlikLab.tsx": () => import("../components/mockups/think-inn-variants/KaranlikLab.tsx"),
  "./components/mockups/think-inn-variants/KomutaMerkezi.tsx": () => import("../components/mockups/think-inn-variants/KomutaMerkezi.tsx")
};
